import { useState } from 'react';
import { View } from 'react-native';
import { router } from 'expo-router';
import { Check, Sparkles } from 'lucide-react-native';
import { aiAnswerSchema, taskSchema, type AiAnswer, type Conversation } from '../../shared/contracts';
import { api } from '../services/api';
import { notify } from '../store/runtime';
import { Button, Card, Chip, Copy, Field, Kite, Row, Title } from '../ui/kit';
export function CopilotPanel({ conversation }: { conversation: Conversation }) {
  const [question, setQuestion] = useState('Resuma as decisões e os próximos passos desta conversa.'); const [answer, setAnswer] = useState<AiAnswer | null>(null); const [recent, setRecent] = useState(false); const [accepted, setAccepted] = useState<number[]>([]);
  return <View style={{ gap: 20 }}><Card><Row><Kite size={80} /><View style={{ flex: 1 }}><Title size={25}>Um pouco de perspectiva.</Title><Copy muted>Kite analisa mensagens desta conversa e aponta de onde veio cada informação.</Copy></View></Row>{conversation.encrypted ? <Copy>A proteção de dispositivos impede o servidor de ler o texto. O copiloto fica indisponível nesta conversa.</Copy> : <><Field label="Pergunte ao Kite" multiline value={question} onChangeText={setQuestion} /><Row><Chip label="Todo o contexto disponível" selected={!recent} onPress={() => setRecent(false)} /><Chip label="Últimas 24h" selected={recent} onPress={() => setRecent(true)} /></Row><Button icon={Sparkles} label="Pedir uma perspectiva" onPress={async () => { setAnswer(await api(`/conversations/${conversation.id}/ai/ask`, aiAnswerSchema, { method: 'POST', body: { question, ...(recent ? { since: Date.now() - 86_400_000 } : {}) } })); setAccepted([]); }} /><Copy muted small>Kite pode errar. Confira as fontes antes de decidir. Nenhuma tarefa é criada sem sua confirmação.</Copy></>}</Card>
    {answer ? <><Card><Title size={20}>O que Kite encontrou</Title><Copy>{answer.answer}</Copy>{answer.citations.length ? <Title size={17}>Fontes na conversa</Title> : <Copy muted small>Nenhuma citação verificável foi retornada.</Copy>}{answer.citations.map((citation, index) => <Card key={`${citation.messageId}-${index}`}><Copy small>“{citation.quote}”</Copy><Button compact secondary label="Ver mensagem citada" onPress={() => router.push({ pathname: '/chat/[id]', params: { id: conversation.id, message: citation.messageId } })} /></Card>)}</Card>{answer.suggestedTasks.length ? <Card><Title size={20}>Próximos passos possíveis</Title>{answer.suggestedTasks.map((task, index) => <View key={index} style={{ gap: 8 }}><Copy>{task.title}</Copy><Button compact secondary icon={Check} disabled={accepted.includes(index)} label={accepted.includes(index) ? 'Tarefa confirmada' : 'Confirmar e criar tarefa'} onPress={async () => { await api(`/conversations/${conversation.id}/tasks`, taskSchema, { method: 'POST', body: { title: task.title, assigneeId: task.assigneeId, sourceMessageId: task.sourceMessageId } }); setAccepted((values) => [...values, index]); notify('Tarefa criada com sua confirmação.'); }} /></View>)}</Card> : null}</> : null}</View>;
}
