import { useMemo, useState } from 'react';
import { ScrollView, View } from 'react-native';
import Svg, { Circle, Line, Text as SvgText } from 'react-native-svg';
import { router } from 'expo-router';
import { Download, Plus, Trash2 } from 'lucide-react-native';
import { z } from 'zod';
import { memorySchema, type Conversation, type Memory } from '../../shared/contracts';
import { useCollection } from '../hooks/data';
import { useSession } from '../providers/session';
import { api } from '../services/api';
import { exportData } from '../services/export-data';
import { Button, Card, Chip, Copy, Field, Row, State, Title } from '../ui/kit';
import { usePalette } from '../ui/theme';
export function MemoriesPanel({ conversation }: { conversation: Conversation }) {
  const data = useCollection(`conversations/${conversation.id}/memories`, memorySchema); const { user } = useSession(); const colors = usePalette();
  const [title, setTitle] = useState(''); const [note, setNote] = useState(''); const [tags, setTags] = useState(''); const [kind, setKind] = useState<Memory['kind']>('reference'); const [related, setRelated] = useState<string[]>([]); const [filter, setFilter] = useState(''); const [selected, setSelected] = useState<string | null>(null);
  const items = useMemo(() => data.items.filter((item) => `${item.title} ${item.note} ${item.tags.join(' ')}`.toLowerCase().includes(filter.toLowerCase())), [data.items, filter]);
  const nodes = useMemo(() => data.items.slice(0, 30).map((memory, index) => ({ memory, x: 65 + index % 4 * 140, y: 65 + Math.floor(index / 4) * 115 })), [data.items]);
  return <View style={{ gap: 20 }}><Card><Title size={20}>O que vale continuar lembrando?</Title><Field label="Título da memória" value={title} onChangeText={setTitle} /><Field label="Contexto e anotações" value={note} onChangeText={setNote} multiline /><Field label="Tags separadas por vírgula" value={tags} onChangeText={setTags} /><Row>{(['reference', 'decision', 'idea'] as const).map((value) => <Chip key={value} label={{ reference: 'Referência', decision: 'Decisão', idea: 'Ideia' }[value]} selected={kind === value} onPress={() => setKind(value)} />)}</Row>{data.items.length ? <><Copy muted small>Conectar a outras memórias</Copy><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 7 }}>{data.items.map((memory) => <Chip key={memory.id} label={memory.title.slice(0, 30)} selected={related.includes(memory.id)} onPress={() => setRelated(related.includes(memory.id) ? related.filter((id) => id !== memory.id) : [...related, memory.id])} />)}</View></> : null}<Button label="Guardar memória" icon={Plus} onPress={async () => { await api(`/conversations/${conversation.id}/memories`, memorySchema, { method: 'POST', body: { title, note, tags: tags.split(',').map((tag) => tag.trim()).filter(Boolean), kind, relatedIds: related } }); setTitle(''); setNote(''); setTags(''); setRelated([]); }} /></Card>
    {nodes.length ? <Card><Row style={{ justifyContent: 'space-between' }}><Title size={20}>Mapa de conexões</Title><Button compact secondary label="Exportar" icon={Download} onPress={() => exportData(`morrow-memory-${conversation.id}.json`, { exportedAt: new Date().toISOString(), conversationId: conversation.id, memories: data.items })} /></Row><ScrollView horizontal><Svg width={570} height={Math.max(190, Math.ceil(nodes.length / 4) * 115 + 40)}>{nodes.flatMap((node) => node.memory.relatedIds.map((id) => { const target = nodes.find((candidate) => candidate.memory.id === id); return target ? <Line key={`${node.memory.id}-${id}`} x1={node.x} y1={node.y} x2={target.x} y2={target.y} stroke={colors.border} strokeWidth={2} /> : null; }))}{nodes.map((node) => <Circle key={node.memory.id} cx={node.x} cy={node.y} r={26} fill={node.memory.kind === 'decision' ? colors.accent : colors.elevated} stroke={selected === node.memory.id ? colors.text : colors.secondary} strokeWidth={2} onPress={() => { setSelected(node.memory.id); setFilter(''); }} />)}{nodes.map((node) => <SvgText key={`${node.memory.id}-label`} x={node.x} y={node.y + 44} fontSize={10} textAnchor="middle" fill={colors.text}>{node.memory.title.slice(0, 21)}</SvgText>)}</Svg></ScrollView><Copy muted small>Toque em um ponto para destacar sua memória. As linhas são vínculos definidos pela equipe.</Copy></Card> : null}
    <Field label="Buscar memórias e tags" value={filter} onChangeText={setFilter} />{data.loading ? <State loading /> : data.error ? <State error={data.error} /> : !items.length ? <State title="Um lugar para as boas ideias ficarem." detail="Guarde uma referência, registre uma decisão ou transforme uma mensagem em memória." /> : items.map((memory) => <Card key={memory.id} style={selected === memory.id ? { borderColor: colors.accent } : undefined}><Row><Chip label={{ reference: 'Referência', decision: 'Decisão', idea: 'Ideia' }[memory.kind]} /><Copy muted small>{new Date(memory.createdAt).toLocaleDateString('pt-BR')}</Copy></Row><Title size={20}>{memory.title}</Title><Copy>{memory.note}</Copy><Row style={{ flexWrap: 'wrap' }}>{memory.tags.map((tag) => <Chip key={tag} label={`#${tag}`} onPress={() => setFilter(tag)} />)}</Row>{memory.sourceMessageIds.map((id) => <Button key={id} compact secondary label="Abrir fonte da memória" onPress={() => router.push({ pathname: '/chat/[id]', params: { id: conversation.id, message: id } })} />)}{memory.authorId === user?.uid || conversation.ownerId === user?.uid ? <Button compact secondary icon={Trash2} label="Remover memória" onPress={() => api(`/conversations/${conversation.id}/memories/${memory.id}`, z.object({ deleted: z.boolean() }), { method: 'DELETE' })} /> : null}</Card>)}</View>;
}
