import { useState } from 'react';
import { View } from 'react-native';
import { Plus } from 'lucide-react-native';
import { pollSchema, type Conversation } from '../../shared/contracts';
import { useCollection, useNow } from '../hooks/data';
import { useSession } from '../providers/session';
import { api } from '../services/api';
import { Button, Card, Chip, Copy, Field, Row, State, Title } from '../ui/kit';
export function PollsPanel({ conversation }: { conversation: Conversation }) {
  const now = useNow();
  const data = useCollection(`conversations/${conversation.id}/polls`, pollSchema); const { user } = useSession(); const [question, setQuestion] = useState(''); const [options, setOptions] = useState(''); const [availability, setAvailability] = useState(false); const [closes, setCloses] = useState('');
  return <View style={{ gap: 20 }}><Card><Title size={20}>Encontre um ponto em comum.</Title><Row><Chip label="Votação" selected={!availability} onPress={() => setAvailability(false)} /><Chip label="Disponibilidade" selected={availability} onPress={() => setAvailability(true)} /></Row><Field label={availability ? 'Qual reunião vamos marcar?' : 'Pergunta da votação'} value={question} onChangeText={setQuestion} /><Field label={availability ? 'Horários (um por linha)' : 'Opções (uma por linha, 2 a 8)'} multiline value={options} onChangeText={setOptions} placeholder={'Segunda, 18h\nTerça, 20h'} /><Field label="Encerramento opcional (AAAA-MM-DD HH:MM)" value={closes} onChangeText={setCloses} /><Button label="Abrir votação" icon={Plus} onPress={async () => { const closesAt = closes ? new Date(closes.replace(' ', 'T')).getTime() : null; if (closesAt !== null && !Number.isFinite(closesAt)) throw new Error('Confira o horário de encerramento.'); await api(`/conversations/${conversation.id}/polls`, pollSchema, { method: 'POST', body: { question, options: options.split('\n').map((item) => item.trim()).filter(Boolean), type: availability ? 'availability' : 'poll', closesAt } }); setQuestion(''); setOptions(''); }} /></Card>
    {data.loading ? <State loading /> : data.error ? <State error={data.error} /> : !data.items.length ? <State title="Todo mundo pode ter voz." detail="Abra uma votação ou encontre um horário que funcione para a equipe." /> : [...data.items].sort((a, b) => b.createdAt - a.createdAt).map((poll) => {
      const chosen = poll.votes[user?.uid ?? ''] ?? []; const ended = poll.closed || Boolean(poll.closesAt && poll.closesAt <= now); const voters = Object.keys(poll.votes).length;
      return <Card key={poll.id}><Row><Chip label={poll.type === 'availability' ? 'Horários' : 'Votação'} /><Copy muted small>{ended ? 'Encerrada' : 'Ao vivo'} · {voters} participante(s)</Copy></Row><Title size={20}>{poll.question}</Title>{poll.options.map((option, index) => <Row key={index}><View style={{ flex: 1 }}><Chip label={`${chosen.includes(index) ? '✓ ' : ''}${option}`} selected={chosen.includes(index)} onPress={ended ? undefined : () => { const next = poll.type === 'availability' ? chosen.includes(index) ? chosen.filter((value) => value !== index) : [...chosen, index] : chosen.includes(index) ? [] : [index]; return api(`/conversations/${conversation.id}/polls/${poll.id}/vote`, pollSchema, { method: 'POST', body: { options: next } }); }} /></View><Copy>{Object.values(poll.votes).filter((votes) => votes.includes(index)).length} voto(s)</Copy></Row>)}{poll.closesAt ? <Copy muted small>Até {new Date(poll.closesAt).toLocaleString('pt-BR')}</Copy> : null}{!ended && (poll.authorId === user?.uid || conversation.ownerId === user?.uid) ? <Button secondary compact label="Encerrar votação" onPress={() => api(`/conversations/${conversation.id}/polls/${poll.id}/close`, pollSchema, { method: 'POST' })} /> : null}</Card>;
    })}</View>;
}
