import { useState } from 'react';
import { ScrollView, View, useWindowDimensions } from 'react-native';
import { router } from 'expo-router';
import { ArrowUpRight, Check, Plus, X } from 'lucide-react-native';
import * as Crypto from 'expo-crypto';
import { taskSchema, type Conversation, type Task } from '../../shared/contracts';
import { useCollection, useNow, usePeople } from '../hooks/data';
import { api } from '../services/api';
import { Button, Card, Chip, Copy, Field, IconButton, Row, State, Title } from '../ui/kit';
import { usePalette } from '../ui/theme';
const statusLabels = { todo: 'A fazer', doing: 'Em movimento', done: 'Concluídas' };
const nextStatus = { todo: 'doing', doing: 'done', done: 'todo' } as const;
export function TasksPanel({ conversation }: { conversation: Conversation }) {
  const data = useCollection(`conversations/${conversation.id}/tasks`, taskSchema); const people = usePeople(); const colors = usePalette();
  const { width } = useWindowDimensions(); const now = useNow(); const [detailsDue, setDetailsDue] = useState('');
  const [title, setTitle] = useState(''); const [due, setDue] = useState(''); const [assignee, setAssignee] = useState<string | null>(null); const [selected, setSelected] = useState<Task | null>(null); const [check, setCheck] = useState('');
  async function update(task: Task, body: unknown) { const next = await api(`/conversations/${conversation.id}/tasks/${task.id}`, taskSchema, { method: 'PATCH', body }); if (selected?.id === task.id) setSelected(next); }
  const deadline = (date = due) => { if (!date) return null; const value = new Date(`${date}T23:59:00`).getTime(); if (!Number.isFinite(value)) throw new Error('Informe o prazo em AAAA-MM-DD.'); return value; };
  return <View style={{ gap: 20 }}><Card><Title size={20}>Um próximo passo concreto.</Title><Field label="Nova tarefa" value={title} onChangeText={setTitle} placeholder="O que precisa acontecer?" /><Field label="Prazo opcional (AAAA-MM-DD)" value={due} onChangeText={setDue} /><Copy muted small>Responsável</Copy><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 7 }}><Chip label="Sem responsável" selected={!assignee} onPress={() => setAssignee(null)} />{conversation.memberIds.map((uid) => <Chip key={uid} label={people.byId[uid]?.name.split(' ')[0] ?? 'Integrante'} selected={assignee === uid} onPress={() => setAssignee(uid)} />)}</View><Button icon={Plus} label="Criar tarefa" onPress={async () => { await api(`/conversations/${conversation.id}/tasks`, taskSchema, { method: 'POST', body: { title, assigneeId: assignee, dueAt: deadline() } }); setTitle(''); setDue(''); }} /></Card>
    {data.loading ? <State loading /> : data.error ? <State error={data.error} /> : <ScrollView horizontal contentContainerStyle={{ gap: 16, alignItems: 'flex-start', paddingBottom: 12 }}>{(['todo', 'doing', 'done'] as const).map((status) => <View key={status} style={{ gap: 10, width: Math.max(260, Math.min(370, (width - 370) / 3)) }}><Row><Title size={21}>{statusLabels[status]}</Title><Chip label={String(data.items.filter((task) => task.status === status).length)} /></Row>{data.items.filter((task) => task.status === status).map((task) => <Card key={task.id} style={{ borderLeftWidth: 4, borderLeftColor: status === 'done' ? colors.secondary : task.dueAt && task.dueAt < now ? colors.danger : colors.accent }}><Title size={18}>{task.title}</Title><Copy muted small>{task.assigneeId ? people.byId[task.assigneeId]?.name ?? 'Integrante' : 'Sem responsável'}{task.dueAt ? ` · ${new Date(task.dueAt).toLocaleDateString('pt-BR')}` : ' · sem prazo'}</Copy>{task.description ? <Copy>{task.description}</Copy> : null}<Copy muted small>{task.checklist.filter((item) => item.done).length}/{task.checklist.length} itens concluídos</Copy><Row style={{ flexWrap: 'wrap' }}><Button compact label={status === 'todo' ? 'Começar' : status === 'doing' ? 'Concluir' : 'Reabrir'} icon={Check} onPress={() => update(task, { status: nextStatus[status] })} /><Button compact secondary label="Detalhes e checklist" onPress={() => { setSelected(task); setDetailsDue(task.dueAt ? new Date(task.dueAt).toISOString().slice(0, 10) : ''); }} />{task.sourceMessageId ? <IconButton label="Abrir mensagem de origem" icon={ArrowUpRight} onPress={() => router.push({ pathname: '/chat/[id]', params: { id: conversation.id, message: task.sourceMessageId! } })} /> : null}</Row></Card>)}</View>)}</ScrollView>}
    {selected ? <Card><Row style={{ justifyContent: 'space-between' }}><Title size={20}>Detalhes da tarefa</Title><IconButton icon={X} label="Fechar detalhes" onPress={() => { setSelected(null); }} /></Row><Field label="Título da tarefa" value={selected.title} onChangeText={(title) => setSelected({ ...selected, title })} /><Field label="Descrição" value={selected.description} multiline onChangeText={(description) => setSelected({ ...selected, description })} /><Field label="Prazo da tarefa (AAAA-MM-DD)" value={detailsDue} onChangeText={setDetailsDue} /><Copy muted small>Responsável da tarefa</Copy><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 7 }}><Chip label="Sem responsável" selected={!selected.assigneeId} onPress={() => setSelected({ ...selected, assigneeId: null })} />{conversation.memberIds.map((uid) => <Chip key={uid} label={people.byId[uid]?.name.split(' ')[0] ?? 'Integrante'} selected={selected.assigneeId === uid} onPress={() => setSelected({ ...selected, assigneeId: uid })} />)}</View><Button label="Salvar detalhes" onPress={() => update(selected, { title: selected.title, description: selected.description, dueAt: deadline(detailsDue), assigneeId: selected.assigneeId })} />{selected.checklist.map((item) => <Chip key={item.id} label={`${item.done ? '✓ ' : '○ '}${item.text}`} selected={item.done} onPress={() => { return update(selected, { checklist: selected.checklist.map((existing) => existing.id === item.id ? { ...existing, done: !existing.done } : existing) }); }} />)}<Field label="Novo item do checklist" value={check} onChangeText={setCheck} /><Button secondary label="Adicionar ao checklist" onPress={async () => { await update(selected, { checklist: [...selected.checklist, { id: `c_${Crypto.randomUUID().replaceAll('-', '')}`, text: check, done: false }] }); setCheck(''); }} /></Card> : null}
  </View>;
}
