import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useAudioRecorder, useAudioRecorderState, RecordingPresets, requestRecordingPermissionsAsync, setAudioModeAsync } from 'expo-audio';
import { ArrowUpRight, AtSign, CheckCheck, Ellipsis, LayoutGrid, LockKeyhole, MessageSquare, Mic, Paperclip, Pin, Send, Square, Users, Video, X } from 'lucide-react-native';
import { z } from 'zod';
import { memorySchema, messageSchema, taskSchema, type LocalMessage } from '../../../shared/contracts';
import { readMarkerSchema, readReceiptSchema, threadSubscriptionSchema } from '../../../shared/read-state';
import { conversationTitle } from '../../../shared/domain';
import { useCollection, useConversation, useMessages, usePeople, useTyping } from '../../hooks/data';
import { useSession } from '../../providers/session';
import { enqueueMessage } from '../../services/outbox';
import { api } from '../../services/api';
import { pickFile, type SelectedFile } from '../../services/media';
import { notify } from '../../store/runtime';
import { Avatar, Button, Card, Chip, Copy, Field, IconButton, Row, Screen, State, Title } from '../../ui/kit';
import { fonts, usePalette } from '../../ui/theme';
import { MessageMedia } from '../../features/message-media';

export default function ChatScreen() {
  const { id, thread, message: highlighted } = useLocalSearchParams<{ id: string; thread?: string; message?: string }>();
  const { conversation, error } = useConversation(id); const messages = useMessages(conversation); const people = usePeople(); const { user } = useSession(); const colors = usePalette();
  const [text, setText] = useState(''); const [search, setSearch] = useState(''); const [mentionOpen, setMentionOpen] = useState(false); const [mentions, setMentions] = useState<string[]>([]);
  const [files, setFiles] = useState<SelectedFile[]>([]); const [selected, setSelected] = useState<LocalMessage | null>(null); const [edit, setEdit] = useState(''); const [pinnedOnly, setPinnedOnly] = useState(false);
  const typing = useTyping(conversation ? id : ''); const list = useRef<ScrollView>(null); const recorder = useAudioRecorder({ ...RecordingPresets.HIGH_QUALITY, isMeteringEnabled: true }, (status) => { if (status.hasError) notify('A gravação foi interrompida. Tente novamente.'); if (status.isFinished && status.url) { const uri = status.url; void setAudioModeAsync({ allowsRecording: false }); setFiles((existing) => existing.some((file) => file.uri === uri) || existing.length >= 4 ? existing : [...existing, { uri, name: Platform.OS === 'web' ? 'audio.webm' : 'audio.m4a', mimeType: Platform.OS === 'web' ? 'audio/webm' : 'audio/mp4' }]); } }); const recording = useAudioRecorderState(recorder);
  const receipts = useCollection(conversation ? `conversations/${id}/readReceipts` : null, readReceiptSchema);
  const markers = useCollection(user ? `users/${user.uid}/readMarkers` : null, readMarkerSchema);
  const subscriptions = useCollection(conversation ? `conversations/${id}/threadSubscriptions` : null, threadSubscriptionSchema);
  const subscribed = subscriptions.items.some((entry) => entry.uid === user?.uid && entry.threadId === thread && entry.subscribed);
  const visible = useMemo(() => messages.items.filter((item) => (thread ? item.id === thread || item.threadId === thread : !item.threadId) && (!pinnedOnly || item.pinned) && (!search || `${item.text} ${item.attachments.map((attachment) => attachment.transcript ?? '').join(' ')}`.toLowerCase().includes(search.toLowerCase()))), [messages.items, thread, pinnedOnly, search]);
  useEffect(() => {
    if (!conversation || !messages.items.length) return;
    const timeout = setTimeout(() => { void api(`/conversations/${id}/read`, z.object({ read: z.boolean() }), { method: 'POST', body: { threadId: thread ?? null } }).catch(() => undefined); }, 700);
    return () => clearTimeout(timeout);
  }, [id, thread, conversation, messages.items.length]);
  useEffect(() => { if (!search && !highlighted) list.current?.scrollToEnd({ animated: true }); }, [visible.length, search, highlighted]);
  const send = useCallback(async () => {
    if (!conversation) return;
    await enqueueMessage(conversation, text.trim(), { mentions, threadId: thread ?? null, replyToId: thread ?? null, files });
    setText(''); setFiles([]); setMentions([]); setMentionOpen(false); typing.update(false);
  }, [conversation, text, mentions, thread, files, typing]);
  async function record() {
    if (recording.isRecording) {
      await recorder.stop(); await setAudioModeAsync({ allowsRecording: false });
      if (recorder.uri) setFiles((existing) => [...existing.filter((file) => file.uri !== recorder.uri), { uri: recorder.uri!, name: Platform.OS === 'web' ? 'audio.webm' : 'audio.m4a', mimeType: Platform.OS === 'web' ? 'audio/webm' : 'audio/mp4', duration: recording.durationMillis / 1000 }]);
    } else {
      if (files.length >= 4) throw new Error('Envie até quatro arquivos por mensagem.');
      const permission = await requestRecordingPermissionsAsync(); if (!permission.granted) throw new Error('Permita o microfone para gravar áudio.');
      await setAudioModeAsync({ allowsRecording: true, playsInSilentMode: true }); await recorder.prepareToRecordAsync(); recorder.record({ forDuration: 120 });
    }
  }
  async function mutate(body: unknown) { if (!selected) return; await api(`/conversations/${id}/messages/${selected.id}`, messageSchema, { method: 'PATCH', body }); setSelected(null); }
  if (!conversation) return <Screen title="Sua conversa" back><State error={error} loading={!error} /></Screen>;
  const name = conversationTitle(conversation, people.byId, user?.uid ?? '');
  return <Screen title={thread ? 'Um assunto, seu espaço.' : name} eyebrow={thread ? `TÓPICO / ${name}` : conversation.type === 'group' ? 'EQUIPE / CONVERSA AO VIVO' : 'CONEXÃO / CONVERSA DIRETA'} subtitle={conversation.encrypted ? 'Texto protegido entre dispositivos. Kite e arquivos ficam fora deste modo.' : `${conversation.memberIds.length} integrantes · mensagem visível a todos da conversa`} back scroll={false} action={<Row><IconButton icon={LayoutGrid} label="Abrir espaço da conversa" onPress={() => router.push({ pathname: '/workspace/[id]', params: { id } })} /><IconButton icon={conversation.type === 'group' ? Users : LockKeyhole} label={conversation.type === 'group' ? 'Configurar grupo' : 'Segurança de dispositivos'} onPress={() => router.push({ pathname: conversation.type === 'group' ? '/group/[id]' : '/security/[id]', params: { id } })} /></Row>}>
    <KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={{ gap: 10, paddingBottom: 10 }}><Row style={{ justifyContent: 'space-between' }}><View style={{ flex: 1 }}><Field label="Buscar texto ou transcrição" value={search} onChangeText={setSearch} placeholder="Encontre algo nesta conversa" /></View><IconButton icon={Pin} label="Mostrar mensagens fixadas" onPress={() => setPinnedOnly(!pinnedOnly)} /><IconButton icon={Video} label="Entrar em chamada" onPress={() => router.push({ pathname: '/call/[id]', params: { id } })} /></Row>{thread ? <Row><Button compact secondary label="Voltar à conversa" onPress={() => router.replace({ pathname: '/chat/[id]', params: { id } })} /><Button compact secondary label={subscribed ? 'Deixar de acompanhar' : 'Acompanhar tópico'} onPress={() => api(`/conversations/${id}/threads/${thread}/subscribe`, z.object({ subscribed: z.boolean() }), { method: 'POST', body: { subscribed: !subscribed } })} /></Row> : null}</View>
    <ScrollView ref={list} style={{ flex: 1 }} keyboardShouldPersistTaps="handled" contentContainerStyle={{ paddingVertical: 16, gap: 18, flexGrow: 1 }} onContentSizeChange={() => { if (!search && !highlighted) list.current?.scrollToEnd({ animated: false }); }}>
    {messages.loading ? <State loading /> : messages.error ? <State error={messages.error} /> : !visible.length ? <State title={search ? 'Nada por aqui com esse termo.' : 'O espaço está aberto.'} detail={search ? 'Tente outro texto ou transcrição.' : 'Envie a primeira mensagem. Kite acompanha vocês.'} /> : visible.map((item) => {
      const person = people.byId[item.senderId]; const mine = item.senderId === user?.uid; const replies = messages.items.filter((reply) => reply.threadId === item.id).length;
      const lastThreadRead = markers.items.find((marker) => marker.conversationId === id && marker.threadId === item.id)?.lastReadAt ?? 0;
      const unreadReplies = messages.items.filter((reply) => reply.threadId === item.id && reply.senderId !== user?.uid && reply.createdAt > lastThreadRead).length;
      const readers = receipts.items.filter((receipt) => receipt.uid !== user?.uid && receipt.threadId === item.threadId && receipt.lastReadAt >= item.createdAt);
      const readLabel = readers.length ? `Lida por ${readers.length}` : 'Persistida';
      return <Row key={item.id} style={{ alignItems: 'flex-start', justifyContent: mine ? 'flex-end' : 'flex-start' }}>{!mine ? <Avatar name={person?.name} url={person?.photoUrl} size={32} onPress={() => router.push({ pathname: '/profile/[uid]', params: { uid: item.senderId } })} /> : null}<View style={{ maxWidth: '85%', minWidth: 160, gap: 5 }}><Row style={{ justifyContent: 'space-between' }}><Copy muted small>{mine ? 'Você' : person?.name ?? 'Integrante'} · {new Date(item.createdAt).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })}</Copy>{!item.localStatus && !item.deletedAt ? <Pressable accessibilityRole="button" accessibilityLabel="Ações da mensagem" onPress={() => { setSelected(item); setEdit(item.text); }}><Ellipsis size={18} color={colors.muted} /></Pressable> : null}</Row><Pressable onLongPress={() => { if (!item.localStatus) { setSelected(item); setEdit(item.text); } }} style={{ backgroundColor: mine ? colors.elevated : colors.surface, borderColor: highlighted === item.id ? colors.accent : colors.border, borderWidth: 1, borderRadius: 17, borderTopRightRadius: mine ? 5 : 17, borderTopLeftRadius: mine ? 17 : 5, padding: 15, gap: 10 }}>
        {item.deletedAt ? <Copy muted>Mensagem removida.</Copy> : <>{item.pinned ? <Row><Pin size={12} color={colors.secondary} /><Copy small muted>Fixada</Copy></Row> : null}{item.text ? <Copy>{item.text}</Copy> : null}{item.attachments.map((attachment) => <MessageMedia key={attachment.id} attachment={attachment} conversationId={id} messageId={item.id} />)}{item.mentionedUserIds.length ? <Copy small muted>{item.mentionedUserIds.map((uid) => `@${people.byId[uid]?.name ?? 'integrante'}`).join(' ')}</Copy> : null}{Object.keys(item.reactions).length ? <Copy small>{Object.values(item.reactions).map((reaction) => ({ heart: '♥', spark: '✦', laugh: '☺', check: '✓' }[reaction] ?? reaction)).join(' ')}</Copy> : null}</>}
        {item.localStatus ? <Copy muted small>{item.localStatus === 'failed' ? 'Falha · abra o Blackout Lab' : 'Na fila · aguardando envio'}</Copy> : <Row style={{ justifyContent: 'space-between' }}><Copy muted small>{item.editedAt ? 'Editada · ' : ''}{item.decrypted ? 'Protegida · ' : ''}{mine ? readLabel : ''}</Copy>{mine ? <CheckCheck size={13} color={readers.length ? colors.secondary : colors.muted} /> : null}</Row>}</Pressable>{replies || !thread && !item.deletedAt && !item.localStatus ? <Pressable onPress={() => router.setParams({ thread: item.id })}><Row><MessageSquare size={13} color={colors.secondary} /><Copy small muted>{replies ? `${replies} resposta(s)` : 'Abrir tópico'}{unreadReplies ? ` · ${unreadReplies} nova(s)` : ''}</Copy></Row></Pressable> : null}</View></Row>;
    })}</ScrollView>
    {typing.typing.length ? <Copy muted small>{typing.typing.map((uid) => people.byId[uid]?.name.split(' ')[0] ?? 'Alguém').join(', ')} digitando…</Copy> : null}
    <View style={{ paddingVertical: 14, gap: 10, borderTopWidth: 1, borderColor: colors.border }}>{files.length ? <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}>{files.map((file, index) => <Chip key={file.uri} label={`${file.name} ×`} onPress={() => setFiles(files.filter((_, current) => current !== index))} />)}</View> : null}{mentionOpen ? <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 7 }}>{conversation.memberIds.filter((uid) => uid !== user?.uid).map((uid) => <Chip key={uid} label={`@${people.byId[uid]?.name ?? 'Integrante'}`} selected={mentions.includes(uid)} onPress={() => setMentions(mentions.includes(uid) ? mentions.filter((member) => member !== uid) : [...mentions, uid])} />)}</View> : null}
    <Row><IconButton icon={AtSign} label="Mencionar integrantes" onPress={() => setMentionOpen(!mentionOpen)} /><IconButton icon={Paperclip} label="Anexar arquivo" onPress={async () => { if (conversation.encrypted) throw new Error('Desative a proteção de texto para compartilhar arquivos.'); if (files.length >= 4) throw new Error('Envie até quatro arquivos por mensagem.'); const file = await pickFile(); if (file) setFiles([...files, file]); }} /><IconButton icon={recording.isRecording ? Square : Mic} label={recording.isRecording ? 'Concluir gravação' : 'Gravar áudio'} onPress={async () => { if (conversation.encrypted) throw new Error('A proteção de dispositivos aceita texto.'); await record(); }} /></Row><Row><View style={{ flex: 1, backgroundColor: colors.surface, borderRadius: 13, borderColor: colors.border, borderWidth: 1 }}><TextInput accessibilityLabel="Mensagem" value={text} placeholder={recording.isRecording ? `Gravando ${Math.floor(recording.durationMillis / 1000)}s…` : 'Escreva seu próximo passo…'} placeholderTextColor={colors.muted} onChangeText={(value) => { setText(value); typing.update(Boolean(value)); }} multiline style={{ color: colors.text, fontFamily: fonts.body, fontSize: 14, padding: 14, maxHeight: 110, minHeight: 47 }} /></View><Button compact icon={Send} label="Enviar" disabled={recording.isRecording || !text.trim() && !files.length} onPress={send} /></Row></View>
    </KeyboardAvoidingView>
    <Modal transparent visible={Boolean(selected)} onRequestClose={() => setSelected(null)} animationType="fade"><View style={{ flex: 1, backgroundColor: '#000A', justifyContent: 'center', padding: 22 }}><Card style={{ width: '100%', maxWidth: 550, alignSelf: 'center' }}><Row style={{ justifyContent: 'space-between' }}><Title size={20}>Dê continuidade.</Title><IconButton icon={X} label="Fechar ações" onPress={() => setSelected(null)} /></Row><Copy muted>{selected?.text.slice(0, 180)}</Copy><Row>{(['heart', 'spark', 'laugh', 'check'] as const).map((reaction) => <Button key={reaction} compact secondary label={{ heart: '♥', spark: '✦', laugh: '☺', check: '✓' }[reaction]} onPress={() => mutate({ action: 'reaction', reaction: selected?.reactions[user?.uid ?? ''] === reaction ? null : reaction })} />)}</Row><Button secondary label={selected?.pinned ? 'Desafixar mensagem' : 'Fixar mensagem'} icon={Pin} onPress={() => mutate({ action: 'pin', pinned: !selected?.pinned })} /><Button secondary label="Abrir tópico" icon={MessageSquare} onPress={() => { const root = selected?.threadId ?? selected?.id; setSelected(null); if (root) router.setParams({ thread: root }); }} />
    {!conversation.encrypted ? <><Button secondary label="Transformar em tarefa" icon={ArrowUpRight} onPress={async () => { if (!selected) return; await api(`/conversations/${id}/tasks`, taskSchema, { method: 'POST', body: { title: selected.text.slice(0, 180) || 'Revisar arquivo compartilhado', sourceMessageId: selected.id, assigneeId: user?.uid ?? null } }); setSelected(null); notify('Tarefa criada. Defina os próximos detalhes no espaço.'); }} /><Button secondary label="Guardar como memória" onPress={async () => { if (!selected) return; await api(`/conversations/${id}/memories`, memorySchema, { method: 'POST', body: { title: selected.text.slice(0, 120) || 'Arquivo de referência', note: selected.text, sourceMessageIds: [selected.id], kind: 'reference' } }); setSelected(null); notify('Memória guardada.'); }} /></> : null}
    {selected?.senderId === user?.uid ? <>{!conversation.encrypted ? <><Field label="Editar texto" value={edit} onChangeText={setEdit} multiline /><Button label="Salvar edição" onPress={() => mutate({ action: 'edit', text: edit })} /></> : null}<Button danger label="Remover minha mensagem" onPress={() => mutate({ action: 'delete' })} /></> : null}</Card></View></Modal>
  </Screen>;
}
