import { useState } from 'react';
import { useLocalSearchParams } from 'expo-router';
import { Check, Pause, Play } from 'lucide-react-native';
import { z } from 'zod';
import { focusSchema } from '../../../shared/contracts';
import { focusRemaining } from '../../../shared/domain';
import { useCollection, useConversation, useNow, usePeople, useRealtime } from '../../hooks/data';
import { useSession } from '../../providers/session';
import { api } from '../../services/api';
import { Button, Card, Chip, Copy, Field, Kite, Row, Screen, State, Title } from '../../ui/kit';
const clockOffsetSchema = z.number();
const checkpointSchema = z.object({ conversationId: z.string(), sessionId: z.string(), goal: z.string(), points: z.number() });
export default function FocusScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { conversation, error } = useConversation(id); const data = useRealtime(conversation ? `rooms/${id}/focus` : null, focusSchema); const { user } = useSession(); const people = usePeople();
  const [goal, setGoal] = useState(''); const [minutes, setMinutes] = useState('25'); const offset = useRealtime('.info/serverTimeOffset', clockOffsetSchema); const now = useNow(500) + (offset.value ?? 0);
  const checkpoints = useCollection(user ? `users/${user.uid}/focusCheckpoints` : null, checkpointSchema);
  const history = useCollection(conversation ? `conversations/${id}/focusHistory` : null, focusSchema);
  const remaining = data.value ? focusRemaining(data.value, now) : 0; const ended = data.value?.state === 'completed' || Boolean(data.value && remaining === 0); const host = data.value?.hostId === user?.uid;
  if (!conversation) return <Screen title="Foco compartilhado" back><State error={error} loading={!error} /></Screen>;
  async function action(value: string) { await api(`/conversations/${id}/focus`, focusSchema, { method: 'PATCH', body: { action: value } }); }
  return <Screen title="Um passo de cada vez." back eyebrow="FOCO / UM TEMPO PARA CONSTRUIR" subtitle="Um objetivo, um relógio compartilhado e pequenos checkpoints. Kite acompanha a equipe.">{data.value ? <Card style={{ alignItems: 'center', paddingVertical: 35 }}><Kite size={120} happy={ended} /><Chip label={ended ? 'Ciclo concluído' : data.value.state === 'paused' ? 'Respirando um pouco' : 'Em foco'} selected /><Title size={62}>{String(Math.floor(remaining / 60)).padStart(2, '0')}:{String(remaining % 60).padStart(2, '0')}</Title><Title size={22}>{data.value.goal}</Title><Copy muted>Iniciado por {people.byId[data.value.hostId]?.name ?? 'integrante'}.</Copy>{host && !ended ? <Row><Button label={data.value.state === 'paused' ? 'Retomar' : 'Pausar'} icon={data.value.state === 'paused' ? Play : Pause} onPress={() => action(data.value!.state === 'paused' ? 'resume' : 'pause')} /><Button secondary label="Concluir ciclo" onPress={() => action('complete')} /></Row> : null}<Button icon={Check} label={data.value.completedBy.includes(user?.uid ?? '') ? 'Seu checkpoint está registrado' : 'Registrar meu checkpoint'} disabled={data.value.completedBy.includes(user?.uid ?? '')} onPress={() => action('checkpoint')} /><Copy muted>{data.value.completedBy.length} de {conversation.memberIds.length} integrantes registraram seu passo.</Copy><Row style={{ flexWrap: 'wrap' }}>{data.value.completedBy.map((uid) => <Chip key={uid} label={`✦ ${people.byId[uid]?.name.split(' ')[0] ?? 'Integrante'}`} />)}</Row></Card> : null}{!data.value || ended ? <Card><Title size={21}>Qual é o próximo passo?</Title><Field label="Objetivo compartilhado" value={goal} onChangeText={setGoal} /><Field label="Duração em minutos (1 a 120)" value={minutes} onChangeText={setMinutes} keyboardType="number-pad" /><Button label="Começar um ciclo juntos" icon={Play} onPress={() => api(`/conversations/${id}/focus`, focusSchema, { method: 'POST', body: { goal, durationSeconds: Number(minutes) * 60 } })} /></Card> : null}{data.error ? <Copy>{data.error}</Copy> : null}<Card><Title size={21}>Seu caminho com Kite</Title><Copy>✦ {checkpoints.items.reduce((total, checkpoint) => total + checkpoint.points, 0)} pontos · {checkpoints.items.length} ciclo(s) com checkpoint</Copy><Copy muted small>Cada ciclo com seu checkpoint registra 10 pontos uma única vez, mesmo que você tente de novo.</Copy>{history.items.length ? <><Title size={18}>Ciclos que a equipe concluiu</Title>{[...history.items].sort((a, b) => b.updatedAt - a.updatedAt).slice(0, 5).map((session) => <Copy key={session.id} muted small>✓ {session.goal} · {session.completedBy.length} checkpoint(s)</Copy>)}</> : null}</Card><Copy muted small>O relógio usa o início persistido no servidor. Sair da tela mantém a sessão; voltar recupera o tempo restante.</Copy></Screen>;
}
