import { useEffect, useState } from 'react';
import { Image, Platform, View } from 'react-native';
import { router } from 'expo-router';
import * as LocalAuthentication from 'expo-local-authentication';
import { Bell, Camera, Check, FlaskConical, LogOut, Moon, Shield, Sun, Trash2 } from 'lucide-react-native';
import { z } from 'zod';
import { deviceSchema, preferenceSchema, profileSchema, type Preferences } from '../../shared/contracts';
import { useApiQuery, useConversations } from '../hooks/data';
import { useSession } from '../providers/session';
import { registerPush } from '../providers/notifications';
import { api } from '../services/api';
import { pickPhoto, uploadFile, type SelectedFile } from '../services/media';
import { identityFor, renewIdentity } from '../services/device-identity';
import { writeJournal } from '../services/journal';
import { notify, useRuntime } from '../store/runtime';
import { Avatar, Button, Card, Chip, Copy, Field, Row, Screen, State, Title } from '../ui/kit';
const devicesSchema = z.array(deviceSchema.omit({ token: true }).extend({ pushRegistered: z.boolean() }));
export default function MyProfileScreen() {
  const session = useSession(); const conversations = useConversations(); const preferencesQuery = useApiQuery('/users/me/preferences', preferenceSchema); const devices = useApiQuery('/users/me/devices', devicesSchema); const runtime = useRuntime();
  const [draftPreferences, setPreferences] = useState<Preferences | null>(null); const preferences = draftPreferences ?? preferencesQuery.data;
  const [name, setName] = useState(session.profile?.name ?? ''); const [phone, setPhone] = useState(session.profile?.phoneNumber ?? ''); const [birth, setBirth] = useState(session.profile?.birthDate ?? ''); const [photo, setPhoto] = useState<SelectedFile | null>(null); const [selfId, setSelfId] = useState('');
  useEffect(() => { if (session.user) void identityFor(session.user.uid).then((identity) => setSelfId(identity.deviceId)); }, [session.user]);
  async function appearance(theme: 'dark' | 'light', biometric: boolean) { if (!session.user) return; runtime.set({ theme, biometric }); await writeJournal(session.user.uid, 'appearance', JSON.stringify({ theme, biometric })); }
  return <Screen title="Seu espaço, seu ritmo." eyebrow="PERFIL / PREFERÊNCIAS" tabs subtitle="Escolha como aparecer, quando receber novidades e quais dispositivos continuam com você."><Card><Row><Avatar name={session.profile?.name} url={session.profile?.photoUrl} size={72} /><View style={{ flex: 1 }}><Title size={23}>{session.profile?.name}</Title><Copy muted>{session.profile?.email}</Copy></View></Row>{photo ? <Image source={{ uri: photo.uri }} style={{ height: 80, width: 80, borderRadius: 20 }} /> : null}<Button secondary icon={Camera} label="Trocar minha foto" onPress={async () => { const selected = await pickPhoto(); if (selected) setPhoto(selected); }} /><Field label="Nome" value={name} onChangeText={setName} /><Field label="Celular com país" value={phone} onChangeText={setPhone} keyboardType="phone-pad" /><Field label="Nascimento (AAAA-MM-DD)" value={birth} onChangeText={setBirth} /><Button label="Salvar meu perfil" icon={Check} onPress={async () => { await api('/users/me', profileSchema, { method: 'PUT', body: { name, phoneNumber: phone, birthDate: birth, photoUrl: photo ? (await uploadFile(photo, 'profile')).url : session.profile?.photoUrl } }); await session.refresh(); notify('Seu perfil está atualizado.'); }} /></Card>
    <Card><Title size={22}>Seu ritmo de notificações</Title>{preferencesQuery.error ? <State error={preferencesQuery.error} /> : preferencesQuery.loading ? <State loading /> : null}<Button secondary icon={Bell} label="Ativar push neste dispositivo" onPress={async () => { await registerPush(); await devices.refresh(); notify('Dispositivo registrado para push.'); }} />{preferences ? <><Chip label={preferences.pushEnabled ? 'Push pessoal: ativo' : 'Push pessoal: pausado'} selected={preferences.pushEnabled} onPress={() => setPreferences({ ...preferences, pushEnabled: !preferences.pushEnabled })} /><Chip label={preferences.hidePreview ? 'Prévia do texto: ocultada' : 'Prévia do texto: visível'} selected={preferences.hidePreview} onPress={() => setPreferences({ ...preferences, hidePreview: !preferences.hidePreview })} /><Chip label={preferences.quietEnabled ? 'Horário de silêncio: ativo' : 'Horário de silêncio: desativado'} selected={preferences.quietEnabled} onPress={() => setPreferences({ ...preferences, quietEnabled: !preferences.quietEnabled })} /><TimeField label="Início do silêncio (HH:MM)" value={preferences.quietStart} onChange={(quietStart) => setPreferences({ ...preferences, quietStart })} /><TimeField label="Fim do silêncio (HH:MM)" value={preferences.quietEnd} onChange={(quietEnd) => setPreferences({ ...preferences, quietEnd })} /><Copy muted small>Silenciar uma conversa para você</Copy><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 7 }}>{conversations.items.map((conversation) => <Chip key={conversation.id} label={conversation.name || 'Conversa direta'} selected={preferences.mutedConversationIds.includes(conversation.id)} onPress={() => setPreferences({ ...preferences, mutedConversationIds: preferences.mutedConversationIds.includes(conversation.id) ? preferences.mutedConversationIds.filter((id) => id !== conversation.id) : [...preferences.mutedConversationIds, conversation.id] })} />)}</View><Button label="Salvar preferências" onPress={async () => { await api('/users/me/preferences', preferenceSchema, { method: 'PUT', body: { ...preferences, utcOffsetMinutes: -new Date().getTimezoneOffset() } }); notify('Seu ritmo está salvo.'); }} /></> : null}<Copy muted small>As preferências pessoais respeitam a política de cada grupo. Mensagens durante o silêncio aguardam uma nova tentativa após o horário escolhido.</Copy></Card>
    <Card><Title size={22}>Aparência e privacidade</Title><Row><Button compact secondary icon={runtime.theme === 'dark' ? Sun : Moon} label={runtime.theme === 'dark' ? 'Modo claro' : 'Modo grafite'} onPress={() => appearance(runtime.theme === 'dark' ? 'light' : 'dark', runtime.biometric)} />{Platform.OS !== 'web' ? <Button compact secondary icon={Shield} label={runtime.biometric ? 'Desativar bloqueio' : 'Bloqueio biométrico'} onPress={async () => { if (!runtime.biometric && (!await LocalAuthentication.hasHardwareAsync() || !await LocalAuthentication.isEnrolledAsync())) throw new Error('Cadastre uma biometria no dispositivo para ativar o bloqueio.'); await appearance(runtime.theme, !runtime.biometric); }} /> : null}</Row><Copy muted small>O bloqueio protege a abertura do app ao voltar do segundo plano. A fila e as chaves possuem seu próprio armazenamento protegido.</Copy></Card>
    <Card><Title size={22}>Seus dispositivos</Title>{session.error ? <Copy>{session.error}</Copy> : null}{devices.error ? <State error={devices.error} /> : devices.loading ? <State loading /> : null}{devices.data?.map((device) => <View key={device.id} style={{ gap: 8, paddingVertical: 9 }}><Row><Copy>{device.label}</Copy><Chip label={device.id === selfId ? 'Este dispositivo' : device.enabled ? 'Ativo' : 'Revogado'} /></Row><Copy muted small>Push {device.pushRegistered ? 'registrado' : 'sem registro'} · {device.platform}</Copy>{device.enabled && device.id !== selfId ? <Button compact danger label="Revogar dispositivo" icon={Trash2} onPress={async () => { await api(`/users/me/devices/${device.id}`, z.object({ revoked: z.boolean() }), { method: 'DELETE' }); await devices.refresh(); }} /> : null}</View>)}{devices.data?.some((device) => device.id === selfId && !device.enabled) ? <><Copy muted>Esta identidade foi revogada. Uma identidade nova recebe apenas novas mensagens; o histórico protegido com a chave anterior deixará de abrir neste dispositivo.</Copy><Button secondary label="Registrar nova identidade neste dispositivo" onPress={async () => { if (!session.user) return; const identity = await renewIdentity(session.user.uid); await session.refresh(); setSelfId(identity.deviceId); await devices.refresh(); notify('Nova identidade registrada. Confira o novo fingerprint com a outra pessoa.'); }} /></> : null}</Card><Button secondary icon={FlaskConical} label="Abrir Blackout Lab" onPress={() => router.push('/sync')} /><Button danger icon={LogOut} label="Sair da minha conta" onPress={session.logout} />
  </Screen>;
}

function TimeField({ label, value, onChange }: { label: string; value: number; onChange: (minute: number) => void }) {
  const [text, setText] = useState(String(Math.floor(value / 60)).padStart(2, '0') + ':' + String(value % 60).padStart(2, '0'));
  return <Field label={label} value={text} onChangeText={(next) => { setText(next); const match = next.match(/^(\d{2}):(\d{2})$/); onChange(match && Number(match[1]) < 24 && Number(match[2]) < 60 ? Number(match[1]) * 60 + Number(match[2]) : NaN); }} />;
}
