import { useSyncExternalStore } from 'react';
import { View } from 'react-native';
import { Radio, RefreshCw, Trash2, WifiOff } from 'lucide-react-native';
import { discardEntry, outboxSnapshot, retryEntries, subscribeOutbox, setBlackout } from '../services/outbox';
import { useRuntime } from '../store/runtime';
import { Button, Card, Chip, Copy, Kite, Row, Screen, State, Title } from '../ui/kit';
export default function SyncScreen() {
  const entries = useSyncExternalStore(subscribeOutbox, outboxSnapshot, outboxSnapshot); const runtime = useRuntime();
  return <Screen title="Blackout Lab." back eyebrow="LABORATÓRIO / CONTINUE SEM SINAL" subtitle="Corte o envio, escreva, reinicie o app e recupere. A fila é persistente e cada mensagem mantém seu ID."><Card><Row><Kite size={75} /><View style={{ flex: 1 }}><Title size={24}>{runtime.blackout ? 'O mundo pode esperar.' : 'Tudo em movimento.'}</Title><Copy muted>{entries.length} pendente(s) · {runtime.online ? 'Rede disponível' : 'Sem rede'}</Copy></View></Row><Button label={runtime.blackout ? 'Restaurar sincronização' : 'Ativar Blackout'} icon={runtime.blackout ? Radio : WifiOff} onPress={() => setBlackout(!runtime.blackout)} /><Copy muted small>Blackout suspende os listeners de mensagens e o envio da fila. O acesso ao app e às configurações continua disponível.</Copy><Button secondary icon={RefreshCw} label="Tentar enviar novamente" disabled={runtime.blackout || !runtime.online} onPress={retryEntries} />{runtime.syncError ? <Copy>{runtime.syncError}</Copy> : null}</Card>{!entries.length ? <State title="Fila vazia. Caminho livre." detail="Ative o Blackout e envie uma mensagem para testar a recuperação." /> : entries.map((entry) => <Card key={entry.input.id}><Row><Chip label={entry.terminal ? 'Precisa de você' : 'Aguardando envio'} selected /><Copy muted small>{entry.attempt} tentativa(s)</Copy></Row><Copy>{entry.input.text || entry.preview || 'Texto protegido'}</Copy><Copy muted small>{entry.input.id} · {entry.files.length} arquivo(s)</Copy>{entry.error ? <Copy>{entry.error}</Copy> : null}<Button secondary compact icon={Trash2} label="Descartar esta mensagem" onPress={() => discardEntry(entry.input.id)} /></Card>)}</Screen>;
}
