import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import config from '../firebaseConfig.json';
import { aiAnswerSchema, attachmentSchema, messageSchema } from '../shared/contracts';

const accounts = z.array(z.object({ email: z.string(), password: z.string() })).parse(JSON.parse(await readFile('.local/fixtures.json', 'utf8')));
const scenario = z.object({ directId: z.string() }).parse(JSON.parse(await readFile('.local/scenario.json', 'utf8')));
const base = process.env.TEST_API_URL || 'http://localhost:4000/api';
const login = await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=${config.apiKey}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...accounts[0], returnSecureToken: true }) });
const { idToken } = z.object({ idToken: z.string() }).parse(await login.json());
async function call<T>(path: string, schema: z.ZodType<T>, body: unknown): Promise<T> {
  const response = await fetch(`${base}${path}`, { method: 'POST', headers: { Authorization: `Bearer ${idToken}`, 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
  if (!response.ok) throw new Error(`${path}: HTTP ${response.status}`);
  return schema.parse(await response.json());
}
const prefix = `/conversations/${scenario.directId}`;
const cycle = `TERRA-${randomUUID().slice(0, 8)}`;
const text = `A decisão do ciclo ${cycle} é entregar na sexta-feira. Bento revisará o canvas. Aurora validará o login.`;
const message = await call(`${prefix}/messages`, messageSchema, { id: `m_ai_${randomUUID().replaceAll('-', '')}`, text });
const answer = await call(`${prefix}/ai/ask`, aiAnswerSchema, { question: `Resuma somente a decisão do ciclo ${cycle}, cite o trecho correspondente e proponha as duas tarefas para confirmação.`, since: message.createdAt });
assert.ok(answer.citations.some((citation) => citation.messageId === message.id && text.includes(citation.quote)));
assert.ok(answer.suggestedTasks.length >= 2);
console.log('PASS: live AI recap, verified source quotation and task proposals.');
const form = new FormData(); form.append('file', new Blob([await readFile('.local/speech.mp3')], { type: 'audio/mpeg' }), 'speech.mp3'); form.append('purpose', 'attachment'); form.append('conversationId', scenario.directId);
const upload = await fetch(`${base}/media`, { method: 'POST', headers: { Authorization: `Bearer ${idToken}` }, body: form });
assert.equal(upload.status, 201);
const audio = attachmentSchema.parse(await upload.json());
const recorded = await call(`${prefix}/messages`, messageSchema, { id: `m_audio_${randomUUID().replaceAll('-', '')}`, text: '', attachments: [audio] });
const transcriptionSchema = z.object({ transcript: z.string(), segments: z.array(z.object({ start: z.number(), end: z.number(), text: z.string() })) });
const transcription = await call(`${prefix}/ai/transcribe`, transcriptionSchema, { assetId: audio.id, messageId: recorded.id });
assert.match(transcription.transcript.toLowerCase(), /sexta/); assert.match(transcription.transcript.toLowerCase(), /bento/);
assert.ok(transcription.segments.length); assert.ok(transcription.segments.every((segment) => segment.end >= segment.start));
console.log('PASS: real speech bytes transcribed with timestamps.');
await writeFile('docs/evidence/ai-verification.json', JSON.stringify({ checkedAt: new Date().toISOString(), api: base, source: { id: message.id, text }, answer, audio: { messageId: recorded.id, size: audio.size, mimeType: audio.mimeType, fixture: 'Synthetic Portuguese speech used only as input; transcript generated by Gemini.' }, transcription }, null, 2));
